
build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs (details from git)***************"
  contactDetails:
    name: "Reina Aiswarya - product owner"
    email: "aiswarya@eazybank.com"
  onCallSupport:
    - (453) 555-1234
    - (236) 523-1345
